feat(frontend): Styled a navbar component with different UI for logge…
bsoc-bitbyte/busify pull request #18
Opened 2023-05-31 19:53 UTC by younome71

Have designed the UI of the Nav-bar. 
Created a sign-in button for the users and also different UI for signed-in users and non-signed-in users.

2023-06-01 03:28 UTC, prajjwalkapoor requested changes
@younome71 Do the required changes.

2023-06-01 03:28 UTC, prajjwalkapoor commented on frontend/google_icon.png
Move this icon to the assets folder.

2023-06-01 03:28 UTC, prajjwalkapoor commented on frontend/src/components/Navbar/index.tsx
> +        A centrailed bus ticket booking system
See Figma design, it is not there. Remove this.

2023-06-01 03:28 UTC, prajjwalkapoor commented on frontend/src/components/Navbar/index.tsx
> +            style={{fontSize: 40, color: 'rgba(214, 202, 202, 0.788)'}}
This should also be designed as per provided Figma UI.

2023-06-01 03:28 UTC, prajjwalkapoor commented on frontend/src/components/Navbar/index.tsx
> +          variant="contained"
use outlined instead of this.

2023-06-01 03:28 UTC, prajjwalkapoor commented on frontend/src/components/Navbar/index.tsx
> +          color="primary"
it should be secondary.

2023-06-01 03:28 UTC, prajjwalkapoor commented on frontend/src/components/Navbar/index.tsx
> +          <img src="google_icon.png" style={{height: '40px'}} />
Don't add it here, pass it as a prop without any styling with the above button as `startIcon`.

2023-06-01 03:28 UTC, prajjwalkapoor commented on frontend/src/components/Navbar/index.tsx
> +          style={{height: '60px', marginTop: '0.4rem'}}
remove these styles and add an 8px border-radius.

2023-06-01 03:46 UTC, prajjwalkapoor commented
Also, there is one more button on the left side of the google signing button. Implement that also.

2023-06-02 16:17 UTC, prajjwalkapoor commented
@younome71 Any updates?

2023-06-02 16:22 UTC, younome71 commented
@prajjwalkapoor Yes, It would be completed till 2-3 am tomorrow

2023-06-03 06:27 UTC, closed without merging