Styled the default scrollbar
bsoc-bitbyte/busify pull request #27
Opened 2023-06-06 09:56 UTC by Doraemon012

### Changes

- Fixes #26 
- Styled the default scrollbar as per theme of the project

2023-06-08 19:01 UTC, prajjwalkapoor requested changes
Great Work! @Doraemon012.  Just do the one suggested change and we are good to go.

2023-06-08 19:01 UTC, prajjwalkapoor commented on frontend/src/App.tsx
> +import './scroll.css';
No need for this. Because this file doesn't even exist, you can remove this.

2023-06-08 19:22 UTC, Doraemon012 reviewed
Sir, I removed the extra import statement.

2023-06-09 04:35 UTC, prajjwalkapoor approved these changes
LGTM.

2023-06-09 04:38 UTC, merged