[Feat]: Added avatar image in the navbar
bsoc-bitbyte/busify pull request #31
Opened 2023-06-10 07:37 UTC by Doraemon012

### Changes made:

- fix #25 
- Now, the users can see their profile image in the navbar when they are logged in.

2023-06-11 07:01 UTC, mittalvansh commented
LGTM!

2023-06-11 20:48 UTC, prajjwalkapoor requested changes

2023-06-11 20:48 UTC, prajjwalkapoor commented on frontend/package.json
> +    "husky": "^8.0.3",
husky should be present in the dev dependency.

2023-06-11 20:48 UTC, prajjwalkapoor commented on backend/package.json
> +    "husky": "^8.0.3",
husky should be present in the dev dependency.

2023-06-12 10:30 UTC, Doraemon012 commented
Now, I have moved husky to package.json

2023-06-12 11:33 UTC, closed without merging