Updated Contributing.md
bsoc-bitbyte/busify pull request #43
Opened 2023-06-16 16:55 UTC by NightFury742

## Overview

1. This PR fixes  #42.
2. This PR does the following: Updated contributing.md to incorporate for the steps to run the backend server.

## Essential Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [ ] The PR is made from a branch that's **not** called "main/master".

2023-06-17 09:51 UTC, prajjwalkapoor requested changes

2023-06-17 09:51 UTC, prajjwalkapoor commented on Contributing.md
Write here:
After installing docker, run the following command to start database containers.

2023-06-17 09:51 UTC, prajjwalkapoor commented on Contributing.md
> +   npx prisma generate
We don't need Prisma generate command, the migrate command will automatically generate the Prisma client so you can remove this.

2023-06-17 09:51 UTC, prajjwalkapoor commented on Contributing.md
>     npm install
It should be the first step after moving to the backend directory so move this up.

2023-06-17 13:18 UTC, NightFury742 commented
@prajjwalkapoor I have made the requested changes, please review them.

2023-06-19 06:09 UTC, prajjwalkapoor approved these changes
LGTM.

2023-06-19 06:10 UTC, merged