feat: Made HeroContainer component responsive
bsoc-bitbyte/busify pull request #45
Opened 2023-06-17 09:45 UTC by jainvedant392

## Overview

1. This PR fixes or fixes part of #44.
2. This PR does the following: 
    Fixed some bugs in the styles and responsiveness of HeroContainer in Homepage

## Essential Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [x] The PR is made from a branch that's **not** called "main/master".

## Proof that changes are correct

![image](https://github.com/bsoc-bitbyte/busify/assets/129421822/abc7f1cc-355d-40fe-902f-74291be25a4d)
![image](https://github.com/bsoc-bitbyte/busify/assets/129421822/360c1fb3-47c7-41ca-b1bf-f08da237c71a)

## PR Pointers

- If you need a review or an answer to a question, and don't have permissions to assign people, **leave a comment** like the following: "{{Question/comment}} @{{reviewer_username}} PTAL".
- Never force push. If you do, your PR will be closed.

2023-07-01 19:35 UTC, prajjwalkapoor requested changes

2023-07-01 19:35 UTC, prajjwalkapoor commented on frontend/src/pages/Home/index.tsx
> +            sx={{
Don't put sx here, instead put it in styled CTA component.
https://github.com/bsoc-bitbyte/busify/blob/d15a1b516fae2e8f80adc16ef8a30eac7f333906/frontend/src/pages/Home/index.tsx#L122

2023-07-05 12:06 UTC, jainvedant392 commented
will do it by today itself

2023-07-07 08:46 UTC, jainvedant392 commented
@prajjwalkapoor, I have done the changes as requested 
please review then once

2023-07-09 03:49 UTC, prajjwalkapoor approved these changes
LGTM.

2023-07-09 03:50 UTC, merged