Feat(frontend): Created checkout page
bsoc-bitbyte/busify pull request #46
Opened 2023-06-18 09:43 UTC by NightFury742

## Overview

1. This PR fixes or fixes part of #41.
2. This PR does the following: Created the checkout page and added routes to it when the user clicks on the pay now button on the bus details drawer. I have also added a toast which displays an error when the user clicks on the button without adding a passenger.

## Essential Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [ ] The PR is made from a branch that's **not** called "main/master".

## Proof that changes are correct

https://github.com/bsoc-bitbyte/busify/assets/119070798/6c26a1ec-2e53-4b56-aedb-463d783dce33

2023-06-18 09:44 UTC, NightFury742 commented
@parthksingh1 will be working on the ticket breakdown and ticket total component in the checkout page.

2023-06-21 10:24 UTC, NightFury742 commented
@prajjwalkapoor @Bhavik-ag  Please review my pr.
 This is how the website looks,

https://github.com/bsoc-bitbyte/busify/assets/119070798/6c49e212-2c93-42df-be34-582cb22b70c3

2023-07-01 20:29 UTC, prajjwalkapoor requested changes
Nice work @NightFury742! 

I have suggested some changes, just do that.

2023-07-01 20:29 UTC, prajjwalkapoor commented on frontend/src/pages/Checkout/index.tsx
> +                    {Math.ceil(ticketQuantity * 20 * 0.02)}
Don't hardcode the price. It comes with a schedule from the backend. Use that.

2023-07-01 20:29 UTC, prajjwalkapoor commented on frontend/src/pages/Checkout/index.tsx
> +  return (
Make the checkout page mobile responsive.

2023-07-05 11:19 UTC, NightFury742 commented
@prajjwalkapoor I have made the requested changes, please review them.

2023-07-05 13:10 UTC, prajjwalkapoor approved these changes
LGTM.

2023-07-05 13:10 UTC, merged