Feat: Add AdminProtected Route
bsoc-bitbyte/busify pull request #62
Opened 2023-07-05 17:42 UTC by parthksingh1

1. This PR fixes or fixes part of #50 
2. This PR does the following: It adds AdminProtectedRoute to admin Dashboard which redirect the user to homePage when the user is not admin.

## Essential Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [X] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [X] The PR is made from a branch that's **not** called "main/master".

2023-07-09 03:54 UTC, prajjwalkapoor requested changes

2023-07-09 03:54 UTC, prajjwalkapoor commented on frontend/src/App.tsx
> +            element={
remove this test code.

2023-07-09 03:54 UTC, prajjwalkapoor commented on frontend/src/components/AdminProtectedRoute.tsx
> +    return <Navigate to="/" />;
Add a small toast message here

2023-07-14 15:43 UTC, Bhavik-ag commented
@parthksingh1 Any updates?

2024-06-05 07:52 UTC, closed without merging