feat(frontend): added admin schedule page
bsoc-bitbyte/busify pull request #91
Opened 2024-06-13 11:35 UTC by bravichandra12

## Overview

1. This PR fixes or fixes part of #[fill_in_number_here].
2. This PR does the following: [Explain here what your PR does and why]

## Essential Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [x] The PR is made from a branch that's **not** called "main/master".

## Proof that changes are correct
![Screenshot (104)](https://github.com/bsoc-bitbyte/busify/assets/160425198/9f9c886b-ff7f-48a8-8570-f3d8ddd9f530)
![Screenshot (105)](https://github.com/bsoc-bitbyte/busify/assets/160425198/b88708e5-4b02-425a-b184-bef63742d889)

2024-06-13 13:51 UTC, Pratik2026 commented
@bravichandra12, I might not have explicitly mentioned but the issue is to create a complete schedule page by which I meant to create the cards component involved in this schedule page as well.

2024-06-13 14:05 UTC, Pratik2026 requested changes

2024-06-13 14:07 UTC, Pratik2026 commented
Add the cards component as well with dummy data along with the requested changes as mentioned above and make sure to keep the page responsive as currently it does not seem so.

2024-06-13 14:35 UTC, bravichandra12 commented on frontend/src/store/useStore.tsx
> +export default useStore;
Made the changes as mentioned

2024-06-13 14:35 UTC, bravichandra12 commented on frontend/src/store/useStore.tsx
> +  setActive: value => set({active: value}),
Made the changes as mentioned

2024-06-15 05:22 UTC, Pratik2026 commented
@bravichandra12, The card component should have only one card so that we can use that card component as a reusable UI card.

2024-06-15 05:26 UTC, Pratik2026 commented
Also, currently, if we directly visit the schedule page then the selected tab is still the dashboard. This can be fixed by using `useEffect` in schedule page to change the `activeTab` state value according to the URL of the page.

2024-06-15 06:46 UTC, bravichandra12 commented
Ok I will do the changes as mentioned

2024-06-15 08:39 UTC, bravichandra12 commented
@Pratik2026 
The changes are made accordingly

2024-06-15 19:08 UTC, Pratik2026 commented
@bravichandra12, The changes look good to me. However, the layout is not responsive in mobile view. Currently, it's overflowing whenever you switch between the bus details and conductor details tab.

2024-06-16 10:32 UTC, Pratik2026 requested changes

2024-06-16 10:32 UTC, Pratik2026 commented on frontend/src/components/DetailsCards/BusCards/index.tsx
>      height: 279px;
remove this height.

2024-06-16 10:32 UTC, Pratik2026 commented on frontend/src/components/DetailsCards/BusCards/index.tsx
>      height: 20px;
remove this height as well.

2024-06-16 10:32 UTC, Pratik2026 commented on frontend/src/components/DetailsCards/BusCards/index.tsx
> +    // height: 80px;
don't comment out, just completely remove all the commented one.

2024-06-16 10:32 UTC, Pratik2026 commented on frontend/src/pages/AdminSchedule/index.tsx
> +                    lg: '1fr',
let's remove xl and set lg: '1fr 1fr'

2024-06-16 10:36 UTC, Pratik2026 commented on frontend/src/pages/AdminSchedule/index.tsx
> +                  height: '50rem',
remove this height property.

2024-06-16 10:36 UTC, Pratik2026 commented on frontend/src/pages/AdminSchedule/index.tsx
> +                    height: '279px',
remove this height as well.

2024-06-16 10:38 UTC, Pratik2026 commented on frontend/src/pages/AdminSchedule/index.tsx
> +                  height: '50rem',
remove this height

2024-06-16 10:38 UTC, Pratik2026 commented on frontend/src/pages/AdminSchedule/index.tsx
> +                    height: '320px',
replace width with max-width and remove the height

2024-06-16 11:44 UTC, bravichandra12 commented
Made the changes as mentioned

2024-06-16 15:01 UTC, Pratik2026 commented
LGTM.

2024-06-16 15:03 UTC, Pratik2026 approved these changes

2024-06-16 15:05 UTC, merged

2024-06-16 15:06 UTC, Pratik2026 commented
merged, thanks for the contribution @bravichandra12